# Generated by Django 5.0.4 on 2025-01-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_alter_categories_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='category',
        ),
    ]
